### ISSUE TITLE
[Feature]: GitHub Action to create builds

### ISSUE THREAD

**Issue by Illusion47586** [JuliaPluto/PlutoDesktop#21]
### In which process do you want a new feature?

Something else

### Feature / Improvement

Create a GitHub action that can build this application when trying to make a release.

### Version

0.0.2

### Todo
- [ ] Auto-download Julia portable
- [ ] Fix trace file generation
- [ ] Batch file to run `npm install` and `npm run package`
